---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
        stages: [manual]
      - id: check-json
        exclude: (.vscode|.devcontainer)
      - id: no-commit-to-branch
        args:
          - --branch=dev
          - --branch=master
          - --branch=main
          - --branch=rc
          - --branch=production

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        stages: [commit]

  - repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
    rev: v2.2.0
    hooks:
      - id: epp-validate
        additional_dependencies: ["puppet:<8"]
      - id: erb-validate
      - id: puppet-lint
        args:
          - --fail-on-warnings
          - --with-context
          - --no-autoloader_layout-check
      - id: puppet-validate
        additional_dependencies: ["puppet:<8"]
      # - id: r10k-validate
      #   additional_dependencies: ["r10k:<4"]
      - id: ruby-validate
